version: '3'

services:
  web:
    build: .
    command: >
      sh -c "
      python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    environment:
      SECRET_KEY: "sadkjsakjdka2km2m2k2DJJ."
    ports:
      - "8000:8000"
    depends_on:
      - my-postgres

  my-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"