# Generated by Django 5.0.6 on 2024-05-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='station',
            unique_together={('name', 'latitude', 'longitude')},
        ),
    ]
