# Generated by Django 5.0.6 on 2024-05-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_alter_station_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='station',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
