# Generated by Django 5.0.6 on 2024-05-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
