# Generated by Django 5.0.6 on 2024-05-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_alter_station_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('source', 'destination')},
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['source', 'destination'], name='station_rou_source__5e1120_idx'),
        ),
    ]
