# Generated by Django 5.0.6 on 2024-05-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_alter_station_unique_together_alter_station_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='route',
            name='unique_route',
        ),
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_ticket',
        ),
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='traintype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
