# Generated by Django 5.0.6 on 2024-05-25 20:04

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_remove_route_unique_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=station.models.train_image_file_path),
        ),
    ]
